USE [AW_DWH_xprchlik]
GO

/****** Object:  Table [dbo].[dimCountry]    Script Date: 15. 1. 2023 18:45:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[dimCountry](
	[CuontryKey] [int] IDENTITY(1,1) NOT NULL,
	[CountryName] [dbo].[Name] NULL,
	[Code] [varchar](2) NULL,
 CONSTRAINT [PK_dimCountry] PRIMARY KEY CLUSTERED 
(
	[CuontryKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

