USE [AW_DWH_xprchlik]
GO

/****** Object:  Table [dbo].[dimTag]    Script Date: 15. 1. 2023 18:48:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[dimTag](
	[TagKey] [int] IDENTITY(1,1) NOT NULL,
	[TagName] [nvarchar](1000) NULL,
 CONSTRAINT [PK_dimTag] PRIMARY KEY CLUSTERED 
(
	[TagKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

